### ISSUE TITLE
EDCT reporting Buy at stations that are not buying that commodity

### ISSUE THREAD

**Issue by msteele999** [Fi0x/EDCT#112]
### Describe the bug
Buy at stations reporting incorrect / non-existent buys compared to Inara.

### To Reproduce
**Version**: 2.0.0.0
**Steps to reproduce the behavior**:
1. Select Painite as the commodity
2. note Buy at price / supply (they are the same number - suspect that is the bug)
3. check Inara.cz Station Market listings

### Screenshots
EDCT:
![Snag_9aa80a](https://user-images.githubusercontent.com/6474337/205062170-1b44cd52-9466-4ef7-be8e-9407c198c210.png)

Inara:
https://inara.cz/elite/station-market/15683/
![Snag_9abd96](https://user-images.githubusercontent.com/6474337/205062187-6e508993-11e9-4b2f-9efc-6879478a15ff.png)

**Comment by Fi0x** [comment]
Thanks for reporting,

I'm working on it.
Seems like I overlooked a change in the inara-website layout that causes the price to be copied to the quantity.

The fix will probably be ready in a few hours

**Comment by msteele999** [comment]
My pleasure - I'm happy to test once you have it resolved.

**Comment by Fi0x** [comment]
Version 2.0.0.1 is released and this bug should be fixed.

If this or any other problem appears again, please let me know.

**Comment by msteele999** [comment]
downloading and testing now :-)

**Comment by msteele999** [comment]
FYI - I opted to clear the database and reload - it was still showing the old data with the new version so I assumed a data refresh was necessary. It will take a few minutes for the new data to finish loading and then I'll let you know if it looks correct.

Mark
